import { ArrowLeft, ArrowRight, ExternalLink } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import SiteHeader from '../../../components/SiteHeader'
import SiteFooter from '../../../components/SiteFooter'
const liveUrl='https://northstead-commercial-risk.vercel.app'
export default function NorthsteadCaseStudy(){return <main className="booth-public min-h-screen"><SiteHeader/>
<section className="border-b booth-rule bg-[#080808]"><div className="booth-container py-10 sm:py-16 lg:py-20"><Link href="/work" className="booth-text-link"><ArrowLeft className="mr-2 h-3.5 w-3.5"/>Selected work</Link><p className="booth-kicker mt-8">Northstead Commercial Risk / Independent Concept / 2026</p><h1 className="booth-display booth-mobile-heading mt-5 max-w-[960px]">Commercial insurance before insurance products.</h1><p className="booth-copy booth-mobile-copy mt-6 max-w-[700px]">A concept exploring how a commercial insurance proposition can establish relevance, confidence and a clear next step without overwhelming the buyer.</p><p className="mt-4 max-w-[700px] text-[11px] leading-5 text-[#666]">Independent concept work created by Booth Marketing. Northstead Commercial Risk is not presented as a commissioned client project and no performance claims are implied.</p><a href={liveUrl} target="_blank" rel="noreferrer" className="booth-secondary mt-7 inline-flex items-center justify-center">View live concept<ExternalLink className="ml-2 h-4 w-4"/></a></div></section>
<section className="booth-section border-b booth-rule"><div className="booth-container"><a href={liveUrl} target="_blank" rel="noreferrer" className="group block overflow-hidden rounded-lg border booth-rule bg-[#080808]" aria-label="Open Northstead Commercial Risk live concept"><div className="relative aspect-[16/10] overflow-hidden"><Image src="/work/northstead.png" alt="Northstead Commercial Risk concept homepage" fill priority sizes="(min-width:1200px) 1136px, 100vw" className="object-cover object-top transition duration-300 group-hover:scale-[1.005]"/></div></a><div className="grid border-b booth-rule sm:grid-cols-4">{[['Project','Northstead Commercial Risk'],['Sector','Commercial Insurance'],['Type','Independent Concept'],['Year','2026']].map(([t,c])=><div key={t} className="border-t booth-rule py-4 sm:border-l sm:px-4"><p className="booth-kicker">{t}</p><p className="mt-2 text-[12px] text-[#c7c7c7]">{c}</p></div>)}</div></div></section>
<section className="booth-section border-b booth-rule bg-[#080808]"><div className="booth-container grid gap-10 lg:grid-cols-2 lg:gap-16"><div><p className="booth-kicker">01 / Problem</p><h2 className="booth-display mt-4 text-[32px] leading-[1.04] sm:text-[44px]">Complex services can make the buyer work too hard.</h2><p className="booth-copy mt-5 text-[14px] leading-7">Commercial insurance naturally contains detail, terminology and multiple areas of cover. The concept establishes who the proposition is for before asking the buyer to navigate individual products.</p></div><div><p className="booth-kicker">02 / Positioning decision</p><h2 className="booth-display mt-4 text-[32px] leading-[1.04] sm:text-[44px]">Position expertise before products.</h2><p className="booth-copy mt-5 text-[14px] leading-7">The hierarchy moves from commercial risk and buyer relevance to confidence and then action. Products support the proposition rather than becoming the proposition.</p></div></div></section>
<section className="booth-section border-b booth-rule"><div className="booth-container"><p className="booth-kicker">03 / Buyer journey</p><div className="mt-7 border-t booth-rule lg:grid lg:grid-cols-3 lg:border-l">{[['01','Position','Establish the audience and proposition before asking the visitor to decode the service.'],['02','Prove','Use sector context, people and professional hierarchy to support confidence without invented social proof.'],['03','Convert','Keep the route toward a broker conversation obvious rather than competing with multiple equal calls to action.']].map(([n,t,c])=><article key={n} className="border-b booth-rule py-6 lg:min-h-[210px] lg:border-r lg:p-6"><span className="font-mono text-[9px] text-[#626262]">{n}</span><h3 className="booth-display mt-5 text-[26px]">{t}</h3><p className="booth-copy mt-3 text-[13px] leading-6">{c}</p></article>)}</div></div></section>
<section className="booth-section"><div className="booth-container"><div className="border-y booth-rule py-10 lg:flex lg:items-end lg:justify-between lg:gap-10"><div><p className="booth-kicker">Apply the thinking</p><h2 className="booth-display mt-4 max-w-[760px] text-[36px] leading-[1.02] sm:text-[50px]">What would we change about your brokerage website?</h2><p className="booth-copy mt-5 max-w-[620px] text-[14px] leading-7">Start with the current site. We will identify what deserves to stay, what is making the decision harder and what should change first.</p></div><Link href="/website-audit" className="booth-primary mt-7 inline-flex items-center justify-center lg:mt-0">Request Website Audit<ArrowRight className="ml-2 h-4 w-4"/></Link></div></div></section><SiteFooter/></main>}
