import { ArrowRight } from 'lucide-react'
import Link from 'next/link'
import SiteHeader from '../../components/SiteHeader'
import SiteFooter from '../../components/SiteFooter'
const areas=[
['Sales',['Qualify and route incoming leads','Prepare follow-up based on defined rules','Reduce repetitive CRM administration','Prepare information for proposals and sales conversations']],
['Customer service',['Handle predictable enquiries using approved information','Route requests to the right person','Prepare customer updates','Support appointment and request handling']],
['Operations',['Extract information from routine documents','Move approved data between systems','Trigger internal handovers and notifications','Reduce repeated data entry']],
['Administration',['Triage routine inbox activity','Prepare recurring documents and summaries','Organise information for reporting','Reduce repetitive internal processing']],
['Management',['Prepare operational summaries','Surface defined alerts','Make approved internal knowledge easier to retrieve','Improve visibility without assembling every update manually']]
]
export default function WhatWeAutomate(){return <main className="booth-public min-h-screen"><SiteHeader/><section className="border-b booth-rule bg-[#080808]"><div className="booth-container py-12 sm:py-16 lg:py-20"><p className="booth-kicker">What We Automate</p><h1 className="booth-display booth-mobile-heading mt-5 max-w-[900px]">Start with the work your team keeps doing by hand.</h1><p className="booth-copy booth-mobile-copy mt-5 max-w-[720px]">You do not need to choose an AI product. We look at the process, the friction and the systems already involved, then decide whether automation is actually justified.</p></div></section><section className="booth-section border-b booth-rule"><div className="booth-container"><div className="border-t booth-rule">{areas.map(([title,items],i)=><article key={title as string} className="grid gap-5 border-b booth-rule py-7 lg:grid-cols-[70px_260px_1fr]"><span className="font-mono text-[10px] text-[#5f5f5f]">0{i+1}</span><h2 className="booth-display text-[28px]">{title as string}</h2><div className="grid gap-2 sm:grid-cols-2">{(items as string[]).map(x=><div key={x} className="booth-panel p-4 text-[12px] leading-6 text-[#aaa]">{x}</div>)}</div></article>)}</div></div></section><section className="booth-section border-b booth-rule bg-[#080808]"><div className="booth-container grid gap-8 lg:grid-cols-2"><div><p className="booth-kicker">The human role</p><h2 className="booth-display mt-4 text-[36px] leading-[1.04]">Automation should remove handling, not judgement.</h2></div><p className="booth-copy text-[15px] leading-7">Where a decision carries meaningful commercial, customer or operational risk, the workflow can stop for approval, escalate uncertainty or limit what the system is allowed to do. The right level of autonomy depends on the consequence of getting something wrong.</p></div></section><section className="booth-section"><div className="booth-container"><div className="border-y booth-rule py-10 lg:flex lg:items-end lg:justify-between"><div><p className="booth-kicker">Your business will be different</p><h2 className="booth-display mt-4 text-[38px]">Show us the process causing friction.</h2></div><Link href="/automation-audit" className="booth-primary mt-7 inline-flex items-center lg:mt-0">Find an Opportunity<ArrowRight className="ml-2 h-4 w-4"/></Link></div></div></section><SiteFooter/></main>}