import { ArrowRight } from 'lucide-react'
import Link from 'next/link'
import SiteFooter from '../../components/SiteFooter'
import SiteHeader from '../../components/SiteHeader'
const deliverables=[['Positioning and structure','Clarify who the brokerage serves, what makes it relevant and how a serious buyer should move through the site.'],['Messaging','Turn expertise from broker conversations into clear website communication.'],['Responsive design','Give desktop, tablet and mobile visitors an experience designed for the screen they use.'],['Development','Build a fast, maintainable website around the agreed structure and content.'],['Service and sector pages','Give important covers, industries and buyer groups focused routes when they need them.'],['Launch foundations','Forms, metadata, performance, search clarity and responsive QA appropriate to scope.']]
const framework=[['POSITION','Make the brokerage and its fit immediately understandable.'],['PROVE','Surface sector knowledge, people and legitimate evidence.'],['REASSURE','Reduce uncertainty through clarity, process and appropriate regulatory information.'],['CONVERT','Move the right commercial prospect toward a broker conversation.']]
export default function WebsitesPage(){return <main className="booth-public min-h-screen"><SiteHeader/>
<section className="border-b booth-rule bg-[#080808]"><div className="booth-container py-12 sm:py-16 lg:py-20"><p className="booth-kicker">Commercial Insurance Broker Websites</p><h1 className="booth-display booth-mobile-heading mt-5 max-w-[920px]">A website that reflects the brokerage you have actually built.</h1><p className="booth-copy booth-mobile-copy mt-5 max-w-[720px]">For established commercial insurance brokerages whose reputation, people and expertise are stronger than their current website makes obvious.</p></div></section>
<section className="booth-section border-b booth-rule"><div className="booth-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="booth-kicker">01 / Where the gap appears</p><h2 className="booth-display mt-4 text-[32px] leading-[1.04] sm:text-[44px]">The website can become the weakest version of the brokerage.</h2></div><div className="border-t booth-rule">{[['After a referral','The site either reinforces the recommendation or introduces doubt.'],['Before a meeting','Prospects form an opinion before a broker has the chance to explain the business.'],['During comparison','Clearer competitors can appear like safer choices.'],['After outreach','Good outreach can lose momentum when the website feels vague, dated or generic.']].map(([t,c],i)=><div key={t} className="grid gap-2 border-b booth-rule py-5 sm:grid-cols-[42px_170px_1fr]"><span className="font-mono text-[9px] text-[#626262]">0{i+1}</span><h3 className="text-[15px] font-normal">{t}</h3><p className="booth-copy text-[13px] leading-6">{c}</p></div>)}</div></div></section>
<section className="booth-section border-b booth-rule bg-[#080808]"><div className="booth-container"><p className="booth-kicker">02 / Brokerage Website Framework</p><h2 className="booth-display mt-4 max-w-[780px] text-[34px] leading-[1.03] sm:text-[48px]">Position. Prove. Reassure. Convert.</h2><div className="mt-9 border-t booth-rule sm:grid sm:grid-cols-2 sm:border-l lg:grid-cols-4">{framework.map(([t,c],i)=><article key={t} className="border-b booth-rule py-6 sm:min-h-[210px] sm:border-r sm:p-6"><span className="font-mono text-[9px] text-[#626262]">0{i+1}</span><h3 className="booth-display mt-5 text-[24px]">{t}</h3><p className="booth-copy mt-3 text-[13px] leading-6">{c}</p></article>)}</div></div></section>
<section className="booth-section border-b booth-rule"><div className="booth-container"><p className="booth-kicker">03 / What gets built</p><h2 className="booth-display mt-4 max-w-[800px] text-[32px] leading-[1.04] sm:text-[44px]">Enough structure to do the job properly. No complexity for its own sake.</h2><p className="booth-copy mt-5 max-w-[720px] text-[14px] leading-7">We diagnose the current site first, then scope what the brokerage genuinely needs. A targeted improvement should not become a full rebuild without a reason.</p><div className="mt-9 border-t booth-rule md:grid md:grid-cols-2 md:border-l">{deliverables.map(([t,c],i)=><article key={t} className="border-b booth-rule py-6 md:min-h-[170px] md:border-r md:p-6"><span className="font-mono text-[9px] text-[#626262]">0{i+1}</span><h3 className="mt-4 text-[16px] font-normal">{t}</h3><p className="booth-copy mt-3 text-[13px] leading-6">{c}</p></article>)}</div></div></section>
<section className="booth-section border-b booth-rule"><div className="booth-container grid gap-9 lg:grid-cols-2"><div><p className="booth-kicker">04 / Preserve what earned its place</p><h2 className="booth-display mt-4 text-[32px] leading-[1.04] sm:text-[44px]">A rebuild is not an excuse to throw away useful assets.</h2></div><div><p className="booth-copy text-[14px] leading-7">Existing search equity, useful service content, recognisable brand assets and regulatory information can carry forward. Change should have a commercial reason.</p><p className="booth-copy mt-5 text-[14px] leading-7">The objective is a clearer digital version of the brokerage, not a trend-led redesign disconnected from the business.</p></div></div></section>
<section className="booth-section bg-[#080808]"><div className="booth-container"><div className="border-y booth-rule py-10 lg:flex lg:items-end lg:justify-between lg:gap-10"><div><p className="booth-kicker">You may not need a rebuild</p><h2 className="booth-display mt-4 max-w-[760px] text-[36px] leading-[1.02] sm:text-[50px]">Start with the current website.</h2><p className="booth-copy mt-5 max-w-[650px] text-[14px] leading-7">If targeted changes are enough, that should be the recommendation. The audit comes first so scope is based on what the brokerage needs.</p></div><Link href="/website-audit" className="booth-primary mt-7 inline-flex items-center justify-center lg:mt-0">Request Website Audit<ArrowRight className="ml-2 h-4 w-4"/></Link></div></div></section><SiteFooter/></main>}
