import { ArrowRight, ExternalLink } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import SiteHeader from '../../components/SiteHeader'
import SiteFooter from '../../components/SiteFooter'
const projects=[{sector:'Hospitality / Nightlife',name:'Purple Door Leeds',href:'/work/purple-door-leeds',live:'https://purple-door-nine.vercel.app',preview:'/work/purple-door.png'},{sector:'Fitness / Local Business',name:'Graft Haus Gym',href:'/work/graft-haus-gym',live:'https://graft-haus-gym.vercel.app',preview:'/work/graft-haus.png'}]
export default function WorkPage(){return <main className="booth-public min-h-screen"><SiteHeader/>
<section className="border-b booth-rule bg-[#080808]"><div className="booth-container py-12 sm:py-16 lg:py-20"><p className="booth-kicker">Selected Work</p><h1 className="booth-display booth-mobile-heading mt-5 max-w-[960px]">Websites designed around the decision the buyer needs to make.</h1><p className="booth-copy booth-mobile-copy mt-6 max-w-[720px]">Commercial insurance is the focus. The work below shows the positioning, structure, design and development thinking behind that approach.</p></div></section>
<section className="booth-section border-b booth-rule"><div className="booth-container"><div className="grid gap-8 lg:grid-cols-[1.55fr_.75fr] lg:items-center"><Link href="/work/northstead-commercial-risk" className="group block overflow-hidden rounded-lg border booth-rule bg-[#080808]"><div className="relative aspect-[16/10] overflow-hidden"><Image src="/work/northstead.png" alt="Northstead Commercial Risk website concept" fill priority sizes="(min-width:1024px) 65vw, 100vw" className="object-cover object-top transition duration-300 group-hover:scale-[1.005]"/></div></Link><div><p className="booth-kicker">01 / Commercial Insurance / Independent Concept</p><h2 className="booth-display mt-4 text-[36px] leading-[1.02] sm:text-[48px]">Northstead Commercial Risk</h2><p className="booth-copy mt-5 text-[14px] leading-7">A restrained direction that puts commercial risk, buyer relevance and broker conversation ahead of a generic product catalogue.</p><div className="mt-6 border-t booth-rule">{[['Positioning','Commercial risk before products'],['Buyer','Established business owners and MDs'],['Conversion','Broker conversation']].map(([t,c])=><div key={t} className="border-b booth-rule py-4"><p className="booth-kicker">{t}</p><p className="mt-2 text-[12px] text-[#bbb]">{c}</p></div>)}</div><p className="mt-4 text-[10px] leading-5 text-[#666]">Independent concept work. Not a commissioned client project.</p><Link href="/work/northstead-commercial-risk" className="booth-text-link mt-4">View case study<ArrowRight className="ml-2 h-4 w-4"/></Link></div></div></div></section>
<section className="booth-section border-b booth-rule bg-[#080808]"><div className="booth-container"><p className="booth-kicker">02 / Selected Wider Work</p><h2 className="booth-display mt-4 max-w-[720px] text-[32px] leading-[1.04] sm:text-[44px]">Different markets. The same discipline around the decision.</h2><div className="mt-9 border-t booth-rule">{projects.map((p,i)=><article key={p.name} className="grid gap-6 border-b booth-rule py-7 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><div><p className="booth-kicker">0{i+2} / {p.sector}</p><h3 className="booth-display mt-4 text-[28px]">{p.name}</h3><div className="mt-4 flex gap-5"><Link href={p.href} className="booth-text-link">Case study<ArrowRight className="ml-2 h-4 w-4"/></Link><a href={p.live} target="_blank" rel="noreferrer" className="booth-text-link">Live site<ExternalLink className="ml-2 h-3.5 w-3.5"/></a></div></div><Link href={p.href} className="relative order-first block aspect-[16/7] overflow-hidden rounded-lg border booth-rule lg:order-none"><Image src={p.preview} alt={`${p.name} website`} fill sizes="(min-width:1024px) 55vw, 100vw" className="object-cover object-top"/></Link></article>)}</div></div></section>
<section className="booth-section"><div className="booth-container"><div className="border-y booth-rule py-10 lg:flex lg:items-end lg:justify-between lg:gap-10"><div><p className="booth-kicker">Your website</p><h2 className="booth-display mt-4 max-w-[760px] text-[36px] leading-[1.02] sm:text-[50px]">Your website does not need to look like these. It needs to make your buyer's decision easier.</h2></div><Link href="/website-audit" className="booth-primary mt-7 inline-flex items-center justify-center lg:mt-0">Request Website Audit<ArrowRight className="ml-2 h-4 w-4"/></Link></div></div></section><SiteFooter/></main>}
