import Link from 'next/link'
import AdminShell from '@/components/admin/AdminShell'
import { getLeads } from '@/lib/leads'
export const dynamic='force-dynamic';export const revalidate=0
const label=(v:string)=>v.replaceAll('_',' ')
const age=(date:string)=>{const h=Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/36e5));return h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`}
export default async function LeadsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const p=await searchParams;let leads:Awaited<ReturnType<typeof getLeads>>=[];let healthy=true;try{leads=await getLeads()}catch{healthy=false}
 const q=(p.q||'').trim().toLowerCase(),status=p.status||'ALL',type=p.type||'ALL',score=p.score||'ALL',industry=p.industry||'ALL',sort=p.sort||'newest'
 const industries=[...new Set(leads.map(l=>l.industry).filter((value):value is string=>Boolean(value)))].sort()
 let filtered=leads.filter(l=>(!q||[l.name,l.email,l.company,l.websiteUrl,l.challenge].some(v=>String(v||'').toLowerCase().includes(q)))&&(status==='ALL'||l.status===status)&&(type==='ALL'||l.enquiryType===type)&&(score==='ALL'||(l.opportunityScore||'UNSCORED')===score)&&(industry==='ALL'||l.industry===industry))
 filtered=[...filtered].sort((a,b)=>sort==='oldest'?+new Date(a.createdAt)-+new Date(b.createdAt):sort==='company'?a.company.localeCompare(b.company):sort==='score'?['','Low','Medium','High','Very High'].indexOf(b.opportunityScore||'')-['','Low','Medium','High','Very High'].indexOf(a.opportunityScore||''):+new Date(b.createdAt)-+new Date(a.createdAt))
 return <AdminShell section="Leads"><div className="mx-auto max-w-[1320px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] font-bold uppercase tracking-[.22em] text-[#d8cbb7]">Enquiry workspace</p><h1 className="mt-3 text-[36px] font-semibold tracking-[-.05em]">Leads</h1><p className="mt-2 text-[12px] text-[#707177]">Search, qualify and progress every genuine Booth Marketing enquiry.</p></div><span className="rounded-full border border-white/[.07] px-3 py-2 text-[9px] text-[#696a70]">{filtered.length} shown · {leads.length} total</span></div>{!healthy&&<div className="mt-6 rounded-xl border border-[#d92f3c]/20 bg-[#190f11] p-4 text-[11px] text-[#d1a3a8]">Lead data is temporarily unavailable.</div>}
 <form className="mt-7 grid gap-2 rounded-[16px] border border-white/[.075] bg-[#0d0f10] p-3 md:grid-cols-3 xl:grid-cols-[1.5fr_repeat(5,minmax(130px,.65fr))_auto]"><input name="q" defaultValue={p.q||''} placeholder="Search company, contact, email or website" className="min-h-[44px] rounded-xl border border-white/[.08] bg-[#090a0b] px-4 text-[11px] outline-none"/><Select name="status" value={status} values={['ALL','NEW','CONTACTED','QUALIFIED','BOOKED','CLOSED_WON','CLOSED_LOST']}/><Select name="type" value={type} values={['ALL','WEBSITE_AUDIT','AUTOMATION_AUDIT','CONTACT','CALCULATOR']}/><Select name="score" value={score} values={['ALL','UNSCORED','Low','Medium','High','Very High']}/><Select name="industry" value={industry} values={['ALL',...industries]}/><Select name="sort" value={sort} values={['newest','oldest','company','score']}/><button className="min-h-[44px] rounded-xl bg-[#efe3cf] px-4 text-[10px] font-semibold text-[#151515]">Apply</button></form>
 <section className="mt-4 overflow-hidden rounded-[18px] border border-white/[.075] bg-[#0d0f10]"><div className="hidden grid-cols-[1.25fr_.75fr_.8fr_.65fr_.55fr_36px] gap-4 border-b border-white/[.07] px-5 py-3 text-[8px] font-bold uppercase tracking-[.13em] text-[#55565b] md:grid"><span>Company / contact</span><span>Source</span><span>Status</span><span>Score</span><span>Age</span><span/></div>{!filtered.length?<div className="px-6 py-14 text-center text-[12px] text-[#77787e]">{leads.length?'No enquiries match these filters.':'No enquiries yet.'}</div>:<div className="divide-y divide-white/[.06]">{filtered.map(l=><Link href={`/admin/leads/${l.id}`} key={l.id} className="grid gap-3 p-5 hover:bg-white/[.025] md:grid-cols-[1.25fr_.75fr_.8fr_.65fr_.55fr_36px] md:items-center"><div className="min-w-0"><p className="truncate text-[12px] font-semibold">{l.company}</p><p className="mt-1 truncate text-[10px] text-[#68696f]">{l.name} · {l.email}</p></div><span className="w-fit rounded-full border border-[#d92f3c]/15 bg-[#190f11] px-2.5 py-1 text-[8px] uppercase text-[#c9a3a7]">{label(l.enquiryType||'WEBSITE_AUDIT')}</span><span className="w-fit rounded-full border border-white/[.08] px-2.5 py-1 text-[8px] uppercase text-[#8b8c92]">{label(l.status)}</span><p className="text-[10px] text-[#d8cbb7]">{l.opportunityScore||'Not scored'}</p><p className="text-[9px] text-[#5f6066]">{age(l.createdAt)}</p><span>→</span></Link>)}</div>}</section></div></AdminShell>}
function Select({name,value,values}:{name:string;value:string;values:string[]}){return <select name={name} defaultValue={value} className="min-h-[44px] rounded-xl border border-white/[.08] bg-[#090a0b] px-3 text-[10px] outline-none">{values.map(v=><option key={v} value={v}>{label(v)}</option>)}</select>}
