import { ArrowRight, ChevronDown } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import BrokerFAQ from '../components/BrokerFAQ'
import SiteFooter from '../components/SiteFooter'
import SiteHeader from '../components/SiteHeader'

const problems=[['The brokerage has grown. The website hasn’t.','The team, client base and capability have moved forward, but the site still represents an earlier version of the business.'],['Referrals still check the website.','A recommendation may open the door, but prospects still use the site to decide whether the brokerage feels credible and relevant.'],['Your expertise has become a product list.','Lines such as liability, property and fleet say what you can place. They do not show why a commercial client should choose your brokerage.'],['Competitors can look more established online.','A less experienced firm can appear like the safer choice when its positioning, people and sector expertise are easier to understand.']]
const framework=[['POSITION','Make it immediately clear who the brokerage serves and why it is worth choosing.'],['PROVE','Demonstrate sector knowledge, broker expertise and legitimate evidence.'],['REASSURE','Use people, process, credibility and appropriate regulatory information to reduce uncertainty.'],['CONVERT','Move appropriate commercial prospects toward the right broker conversation.']]
const process=[['01','Understand the brokerage','Clients, specialisms, team, sales process and positioning.'],['02','Audit the existing website','Messaging, credibility, services, sectors and enquiry journey.'],['03','Map the buyer journey','How a prospect moves from referral or introduction to broker conversation.'],['04','Design and build','Messaging, structure, visual design and development.'],['05','Review and launch','Responsive QA, forms, journeys, regulatory presentation, SEO foundations and final checks.']]
const comparison=[['“Tailored insurance solutions for businesses of all sizes.”','Clear positioning around the businesses and sectors the brokerage understands.'],['Insurance product catalogue.','Buyer problems, sectors, expertise and connected commercial risks.'],['“Get a Quote.”','Create an appropriate broker conversation.']]
function Heading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="max-w-[820px]"><p className="booth-kicker">{eyebrow}</p><h2 className="booth-display mt-4 text-[clamp(34px,7vw,54px)] leading-[1.03] text-[#2c2926]">{title}</h2>{copy&&<p className="booth-copy mt-5 max-w-[720px] text-[15px] leading-7 sm:text-[16px]">{copy}</p>}</div>}
export default function Page(){return <main className="booth-editorial min-h-screen overflow-x-hidden"><SiteHeader/>
<section className="px-3 pb-3 pt-3 sm:px-5 sm:pb-5"><div className="relative mx-auto min-h-[620px] max-w-[1240px] overflow-hidden rounded-[24px] bg-[#171615] text-white sm:min-h-[680px] lg:min-h-[720px]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_35%,rgba(165,31,45,.38),transparent_35%),linear-gradient(120deg,#171615_0%,#211819_48%,#130f10_100%)]"/><Image src="/ChatGPT_Image_Sep_11,_2026,_05_49_13_PM.png" alt="Red rose" width={1374} height={1145} priority className="absolute bottom-[-2%] right-[-35%] h-auto w-[100%] max-w-[760px] opacity-80 sm:right-[-18%] sm:w-[78%] lg:right-[-2%] lg:w-[58%]"/><div className="relative flex min-h-[620px] items-end p-5 sm:min-h-[680px] sm:p-8 lg:min-h-[720px] lg:p-12"><div className="max-w-[720px] rounded-[20px] border border-white/15 bg-white/[.08] p-5 backdrop-blur-xl sm:p-8 lg:p-10"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#efe3cf]">Websites for Commercial Insurance Brokers</p><h1 className="booth-display mt-4 text-[clamp(40px,10vw,68px)] leading-[.98] text-white">Your brokerage has earned its reputation. <span className="text-[#d6cdc3]">Does your website reflect it?</span></h1><p className="mt-5 max-w-[620px] text-[15px] leading-7 text-[#ded9d4] sm:text-[17px]">We design conversion-focused websites for established commercial insurance brokers that need to look credible, explain their expertise clearly and turn more serious prospects into broker conversations.</p><p className="mt-3 max-w-[580px] text-[13px] leading-6 text-[#aaa29b]">Your brokerage already earns trust offline. Your website should reinforce it online.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/website-audit" className="booth-mobile-stack inline-flex min-h-[48px] items-center justify-center rounded-lg bg-[#fefffc] px-5 text-[13px] font-semibold text-[#1d1c1a]">Request Brokerage Website Audit<ArrowRight className="ml-2 h-4 w-4"/></Link><Link href="/work/northstead-commercial-risk" className="booth-mobile-stack inline-flex min-h-[48px] items-center justify-center rounded-lg border border-white/30 px-5 text-[13px] font-semibold text-white">See Commercial Insurance Concept</Link></div></div></div></div></section>

<section className="py-16 sm:py-24"><div className="mx-auto w-[min(1160px,calc(100%-32px))]"><Heading eyebrow="Problem recognition" title="A strong brokerage can still look ordinary online." copy="The problem is rarely that the brokerage lacks substance. It is that the website does not make that substance obvious to a busy commercial buyer."/><div className="mt-10 border-t booth-rule">{problems.map(([title,copy],i)=><article key={title} className="grid gap-3 border-b booth-rule py-7 sm:grid-cols-[70px_1fr_1fr] sm:gap-7"><span className="text-[12px] text-[#9b958f]">0{i+1}</span><h3 className="booth-display text-[25px] leading-[1.12] text-[#34312e]">{title}</h3><p className="booth-copy max-w-[500px] text-[14px] leading-6">{copy}</p></article>)}</div></div></section>

<section className="bg-white py-16 sm:py-24"><div className="mx-auto grid w-[min(1160px,calc(100%-32px))] gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Heading eyebrow="Referral validation" title="The referral gets you considered. The website helps validate the recommendation." copy="Referrals, introducers, networking and outbound can create trust before a prospect lands on the site. The website should preserve that confidence and make speaking to a broker feel like the obvious next step."/><div className="booth-card p-5 sm:p-7"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#7b1722]">A commercial buyer's journey</p><div className="mt-6 grid gap-0">{['Referral / Introduction','Website Check','Confidence','Broker Conversation'].map((node,i)=><div key={node} className="grid grid-cols-[34px_1fr] items-center border-b booth-rule py-4 last:border-0"><span className="font-serif text-[16px] text-[#a51f2d]">0{i+1}</span><span className="text-[15px] font-medium text-[#34312e]">{node}</span></div>)}</div></div></div></section>

<section className="py-16 sm:py-24"><div className="mx-auto w-[min(1160px,calc(100%-32px))]"><Heading eyebrow="A better broker website" title="Move beyond generic insurance language."/><div className="mt-10 overflow-hidden rounded-[16px] border booth-rule bg-white"><div className="hidden grid-cols-[.8fr_1.2fr] border-b booth-rule bg-[#f7f5ef] px-6 py-4 text-[11px] font-bold uppercase tracking-[.16em] text-[#817b75] sm:grid"><span>Typical</span><span>Better</span></div>{comparison.map(([a,b])=><div key={a} className="grid gap-3 border-b booth-rule p-5 last:border-0 sm:grid-cols-[.8fr_1.2fr] sm:p-6"><p className="text-[13px] leading-6 text-[#8a847e]"><span className="mb-1 block text-[9px] font-bold uppercase tracking-[.15em] text-[#aaa49e] sm:hidden">Typical</span>{a}</p><p className="text-[15px] leading-6 text-[#34312e]"><span className="mb-1 block text-[9px] font-bold uppercase tracking-[.15em] text-[#7b1722] sm:hidden">Better</span>{b}</p></div>)}</div></div></section>

<section className="bg-[#171615] py-16 text-white sm:py-24"><div className="mx-auto w-[min(1160px,calc(100%-32px))]"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#d8cbb7]">Booth Brokerage Website Framework</p><h2 className="booth-display mt-4 max-w-[850px] text-[clamp(38px,7vw,62px)] leading-[1] text-white">Position. Prove. Reassure. Convert.</h2><p className="mt-5 max-w-[700px] text-[15px] leading-7 text-[#aaa39d]">A broker website should make the right buyer understand the fit, trust the people behind the advice and know what to do next.</p><div className="mt-12 grid gap-px overflow-hidden rounded-[16px] bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{framework.map(([t,c],i)=><article key={t} className="bg-[#1d1b1a] p-6"><span className="text-[11px] text-[#8d8580]">0{i+1}</span><h3 className="booth-display mt-8 text-[27px] text-[#f5f1eb]">{t}</h3><p className="mt-3 text-[13px] leading-6 text-[#99918b]">{c}</p></article>)}</div></div></section>

<section className="py-16 sm:py-24"><div className="mx-auto grid w-[min(1160px,calc(100%-32px))] gap-10 lg:grid-cols-2"><div><Heading eyebrow="Commercial insurance expertise" title="We understand how commercial insurance is actually sold."/><p className="booth-copy mt-6 text-[15px] leading-7">Commercial insurance is relationship-led. Referrals matter. Introducers matter. Renewals matter. Prospects often describe operational problems rather than policy terminology, and different sectors bring different exposures.</p><p className="booth-copy mt-4 text-[15px] leading-7">A good website should support the people inside the brokerage and attract appropriate conversations, not simply chase the largest possible number of quote forms.</p></div><div className="booth-card self-end p-6 sm:p-8"><p className="booth-kicker">People are part of the proposition</p><h3 className="booth-display mt-5 text-[clamp(30px,6vw,44px)] leading-[1.04] text-[#34312e]">Experienced brokers should not be hidden behind stock imagery.</h3><p className="booth-copy mt-5 text-[14px] leading-7">Broker profiles, sector knowledge, real process and visible expertise help a commercial buyer understand who they may actually speak to.</p></div></div></section>

<section className="bg-white py-16 sm:py-24"><div className="mx-auto grid w-[min(1160px,calc(100%-32px))] gap-10 lg:grid-cols-[.78fr_1.22fr] lg:items-center"><div><p className="booth-kicker">Flagship proof</p><h2 className="booth-display mt-4 text-[clamp(38px,7vw,58px)] leading-[1] text-[#2c2926]">Northstead Commercial Risk</h2><p className="mt-3 text-[11px] font-bold uppercase tracking-[.15em] text-[#817b75]">Independent Commercial Insurance Brokerage Concept</p><p className="booth-copy mt-6 text-[15px] leading-7">Northstead demonstrates how a brokerage can be positioned around understanding commercial risk and the buyer's operation rather than generic insurance products.</p><p className="mt-5 text-[11px] leading-5 text-[#918b85]">Independent concept work. Not a commissioned client project.</p><Link href="/work/northstead-commercial-risk" className="booth-button mt-7 inline-flex items-center px-5 text-[13px] font-semibold">Explore the Commercial Insurance Concept<ArrowRight className="ml-2 h-4 w-4"/></Link></div><div className="overflow-hidden rounded-[20px] border booth-rule bg-[#f7f5ef] p-2 shadow-[0_8px_30px_rgba(40,30,20,.06)]"><div className="relative aspect-[16/10] overflow-hidden rounded-[14px]"><img src="/work/northstead.png" alt="Northstead Commercial Risk concept homepage" className="h-full w-full object-cover object-top"/></div></div></div></section>

<section className="py-16 sm:py-24"><div className="mx-auto w-[min(1160px,calc(100%-32px))]"><Heading eyebrow="How it works" title="A manageable process for a busy brokerage MD."/><div className="mt-10 border-t booth-rule">{process.map(([n,t,c])=><article key={n} className="grid gap-3 border-b booth-rule py-6 sm:grid-cols-[70px_220px_1fr] sm:gap-7"><span className="text-[12px] text-[#9b958f]">{n}</span><h3 className="booth-display text-[22px] text-[#34312e]">{t}</h3><p className="booth-copy max-w-[570px] text-[14px] leading-6">{c}</p></article>)}</div></div></section>

<section className="bg-white py-16 sm:py-24"><div className="mx-auto grid w-[min(1160px,calc(100%-32px))] gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="booth-kicker">Questions before a rebuild</p><h2 className="booth-display mt-4 text-[clamp(34px,6vw,50px)] leading-[1.03] text-[#2c2926]">The sensible objections are worth answering properly.</h2><p className="booth-copy mt-5 text-[14px] leading-7">A commercial insurance website should support the brokerage's real sales process, not force it into a generic digital funnel.</p></div><div className="text-[#1d1c1a]"><BrokerFAQ/></div></div></section>

<section className="px-3 py-3 sm:px-5 sm:py-5"><div className="mx-auto max-w-[1240px] overflow-hidden rounded-[24px] bg-[#7b1722] px-5 py-14 text-center text-white sm:px-10 sm:py-20"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#eadbd3]">Still deciding whether a rebuild is justified?</p><h2 className="booth-display mx-auto mt-4 max-w-[720px] text-[clamp(38px,8vw,62px)] leading-[1]">Start with your current website.</h2><p className="mx-auto mt-5 max-w-[600px] text-[15px] leading-7 text-[#eadbd3]">We will assess what is working, what is weakening trust and whether the right answer is to keep it, improve it or rebuild it.</p><Link href="/website-audit" className="mt-7 inline-flex min-h-[48px] items-center rounded-lg bg-[#fefffc] px-6 text-[13px] font-semibold text-[#421016]">Request Brokerage Website Audit<ArrowRight className="ml-2 h-4 w-4"/></Link></div></section><SiteFooter/></main>}
