import { ArrowDown, ArrowRight, ArrowUpRight } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import BrokerFAQ from '../components/BrokerFAQ'
import SiteFooter from '../components/SiteFooter'
import SiteHeader from '../components/SiteHeader'

const problems=[['The brokerage has grown. The website hasn’t.','The team, client base and capability have moved forward, but the site still represents an earlier version of the business.'],['Referrals still check the website.','A recommendation may open the door, but prospects still use the site to decide whether the brokerage feels credible and relevant.'],['Your expertise has become a product list.','Lines such as liability, property and fleet say what you can place. They do not show why a commercial client should choose your brokerage.'],['Competitors can look more established online.','A less experienced firm can appear like the safer choice when its positioning, people and sector expertise are easier to understand.']]
const framework=[['POSITION','Make it immediately clear who the brokerage serves and why it is worth choosing.'],['PROVE','Demonstrate sector knowledge, broker expertise and legitimate evidence.'],['REASSURE','Use people, process, credibility and appropriate regulatory information to reduce uncertainty.'],['CONVERT','Move appropriate commercial prospects toward the right broker conversation.']]
const process=[['01','Understand the brokerage','Clients, specialisms, team, sales process and positioning.'],['02','Audit the existing website','Messaging, credibility, services, sectors and enquiry journey.'],['03','Map the buyer journey','How a prospect moves from referral or introduction to broker conversation.'],['04','Design and build','Messaging, structure, visual design and development.'],['05','Review and launch','Responsive QA, forms, journeys, regulatory presentation, SEO foundations and final checks.']]
const comparison=[['“Tailored insurance solutions for businesses of all sizes.”','Clear positioning around the businesses and sectors the brokerage understands.'],['Insurance product catalogue.','Buyer problems, sectors, expertise and connected commercial risks.'],['“Get a Quote.”','Create an appropriate broker conversation.']]
function Heading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="max-w-[840px]"><p className="booth-kicker">{eyebrow}</p><h2 className="booth-display mt-5 text-[clamp(34px,8vw,58px)] leading-[1.02]">{title}</h2>{copy&&<p className="booth-copy mt-5 max-w-[720px] text-[15px] leading-7 sm:text-[16px]">{copy}</p>}</div>}
export default function Page(){return <main className="booth-public min-h-screen overflow-x-hidden"><SiteHeader/>
<section className="relative border-b booth-rule bg-[#080808]"><div className="mx-auto grid min-h-[650px] w-[min(1200px,calc(100%-36px))] items-center gap-8 py-16 lg:min-h-[720px] lg:grid-cols-[.6fr_.4fr] lg:py-20"><div className="relative z-10 max-w-[760px]"><p className="booth-kicker">Websites for Commercial Insurance Brokers</p><h1 className="booth-display mt-5 text-[clamp(43px,10.5vw,76px)] leading-[.96]">Your brokerage has earned its reputation. <span className="text-[#8c8c8c]">Does your website reflect it?</span></h1><p className="mt-7 max-w-[650px] text-[15px] leading-7 text-[#aaa] sm:text-[17px]">We design conversion-focused websites for established commercial insurance brokers that need to look credible, explain their expertise clearly and turn more serious prospects into broker conversations.</p><p className="mt-3 max-w-[590px] text-[12px] leading-6 text-[#6f6f6f]">Your brokerage already earns trust offline. Your website should reinforce it online.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/website-audit" className="booth-primary booth-mobile-stack inline-flex items-center justify-center">Request Website Audit<ArrowUpRight className="ml-2 h-4 w-4"/></Link><Link href="/work/northstead-commercial-risk" className="booth-secondary booth-mobile-stack inline-flex items-center justify-center">View Work<ArrowRight className="ml-2 h-4 w-4"/></Link></div></div><div className="relative hidden h-[520px] lg:block"><div className="absolute inset-y-[8%] left-0 w-px bg-[#242424]"/><Image src="/ChatGPT_Image_Sep_11,_2026,_05_49_13_PM.png" alt="Red rose" width={1374} height={1145} priority sizes="440px" className="absolute right-[-12%] top-1/2 h-auto w-[115%] max-w-[560px] -translate-y-1/2 opacity-75"/><div className="absolute bottom-10 left-7 flex items-center gap-3 font-mono text-[9px] uppercase tracking-[.14em] text-[#666]"><span className="h-1.5 w-1.5 rounded-full bg-[#a51f2d]"/>Reputation / expertise / conversation</div></div></div><div className="mx-auto flex w-[min(1200px,calc(100%-36px))] items-center gap-2 border-t booth-rule py-4 font-mono text-[9px] uppercase tracking-[.14em] text-[#555]">Scroll to review the argument<ArrowDown className="h-3 w-3"/></div></section>

<section className="border-b booth-rule py-16 sm:py-24"><div className="mx-auto w-[min(1200px,calc(100%-36px))]"><Heading eyebrow="01 / Recognition" title="A strong brokerage can still look ordinary online." copy="The problem is rarely that the brokerage lacks substance. It is that the website does not make that substance obvious to a busy commercial buyer."/><div className="mt-12 grid border-l border-t booth-rule md:grid-cols-2">{problems.map(([title,copy],i)=><article key={title} className="min-h-[230px] border-b border-r booth-rule p-6 sm:p-8"><span className="font-mono text-[10px] text-[#606060]">0{i+1}</span><h3 className="booth-display mt-9 max-w-[420px] text-[27px] leading-[1.06]">{title}</h3><p className="booth-copy mt-4 max-w-[440px] text-[13px] leading-6">{copy}</p></article>)}</div></div></section>

<section className="border-b booth-rule py-16 sm:py-24"><div className="mx-auto grid w-[min(1200px,calc(100%-36px))] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><Heading eyebrow="02 / Referral validation" title="The referral gets you considered. The website helps validate the recommendation." copy="Referrals, introducers, networking and outbound can create trust before a prospect lands on the site. The website should preserve that confidence and make speaking to a broker feel like the obvious next step."/><div className="border-l border-t booth-rule">{['Referral / Introduction','Website Check','Confidence','Broker Conversation'].map((node,i)=><div key={node} className="grid min-h-[68px] grid-cols-[48px_1fr] items-center border-b border-r booth-rule px-4"><span className={`font-mono text-[10px] ${i===1?'text-[#c64755]':'text-[#5f5f5f]'}`}>0{i+1}</span><span className="text-[14px] text-[#c9c9c9]">{node}</span></div>)}</div></div></section>

<section className="border-b booth-rule py-16 sm:py-24"><div className="mx-auto w-[min(1200px,calc(100%-36px))]"><Heading eyebrow="03 / Positioning" title="Move beyond generic insurance language."/><div className="mt-12 border-l border-t booth-rule"><div className="hidden grid-cols-[.8fr_1.2fr] border-b border-r booth-rule px-6 py-4 font-mono text-[9px] uppercase tracking-[.14em] text-[#606060] sm:grid"><span>Typical broker website</span><span>Better</span></div>{comparison.map(([a,b])=><div key={a} className="grid gap-4 border-b border-r booth-rule p-6 sm:grid-cols-[.8fr_1.2fr]"><p className="text-[13px] leading-6 text-[#6f6f6f]"><span className="mb-2 block font-mono text-[9px] uppercase tracking-[.12em] text-[#555] sm:hidden">Typical</span>{a}</p><p className="text-[15px] leading-6 text-[#d4d4d4]"><span className="mb-2 block font-mono text-[9px] uppercase tracking-[.12em] text-[#9b4a53] sm:hidden">Better</span>{b}</p></div>)}</div></div></section>

<section className="border-b booth-rule bg-[#080808] py-16 sm:py-24"><div className="mx-auto w-[min(1200px,calc(100%-36px))]"><Heading eyebrow="04 / Booth Brokerage Website Framework" title="Position. Prove. Reassure. Convert." copy="A broker website should make the right buyer understand the fit, trust the people behind the advice and know what to do next."/><div className="mt-12 grid border-l border-t booth-rule sm:grid-cols-2 lg:grid-cols-4">{framework.map(([t,c],i)=><article key={t} className="min-h-[250px] border-b border-r booth-rule p-6"><span className="font-mono text-[10px] text-[#5f5f5f]">0{i+1}</span><h3 className="booth-display mt-12 text-[28px]">{t}</h3><p className="booth-copy mt-4 text-[13px] leading-6">{c}</p></article>)}</div></div></section>

<section className="border-b booth-rule py-16 sm:py-24"><div className="mx-auto grid w-[min(1200px,calc(100%-36px))] gap-12 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><Heading eyebrow="05 / Commercial insurance expertise" title="We understand how commercial insurance is actually sold."/><p className="booth-copy mt-7 max-w-[700px] text-[15px] leading-7">Commercial insurance is relationship-led. Referrals matter. Introducers matter. Renewals matter. Prospects often describe operational problems rather than policy terminology, and different sectors bring different exposures.</p><p className="booth-copy mt-4 max-w-[700px] text-[15px] leading-7">A good website should support the people inside the brokerage and attract appropriate conversations, not simply chase the largest possible number of quote forms.</p></div><div className="border-l border-t booth-rule p-6 sm:p-8"><p className="booth-kicker">People are part of the proposition</p><h3 className="booth-display mt-7 text-[clamp(30px,6vw,45px)] leading-[1.03]">Experienced brokers should not be hidden behind stock imagery.</h3><p className="booth-copy mt-5 text-[13px] leading-6">Broker profiles, sector knowledge, real process and visible expertise help a commercial buyer understand who they may actually speak to.</p></div></div></section>

<section className="border-b booth-rule bg-[#080808] py-16 sm:py-24"><div className="mx-auto w-[min(1200px,calc(100%-36px))]"><div className="grid gap-10 lg:grid-cols-[.62fr_1.38fr] lg:items-end"><div><p className="booth-kicker">06 / Flagship proof</p><h2 className="booth-display mt-5 text-[clamp(38px,7vw,60px)] leading-[1]">Northstead Commercial Risk</h2><p className="mt-4 font-mono text-[9px] uppercase tracking-[.12em] text-[#666]">Independent Commercial Insurance Brokerage Concept</p><p className="booth-copy mt-6 text-[14px] leading-7">Northstead demonstrates how a brokerage can be positioned around understanding commercial risk and the buyer’s operation rather than generic insurance products.</p><p className="mt-5 text-[10px] leading-5 text-[#5f5f5f]">Independent concept work. Not a commissioned client project.</p><Link href="/work/northstead-commercial-risk" className="booth-secondary mt-7 inline-flex items-center justify-center">View Commercial Insurance Concept<ArrowUpRight className="ml-2 h-4 w-4"/></Link></div><div className="border booth-rule bg-[#101010] p-2"><div className="relative aspect-[16/10] overflow-hidden"><img src="/work/northstead.png" alt="Northstead Commercial Risk concept homepage" className="h-full w-full object-cover object-top"/></div></div></div></div></section>

<section className="border-b booth-rule py-16 sm:py-24"><div className="mx-auto w-[min(1200px,calc(100%-36px))]"><Heading eyebrow="07 / Process" title="A manageable process for a busy brokerage MD."/><div className="mt-12 border-t booth-rule">{process.map(([n,t,c])=><article key={n} className="grid gap-3 border-b booth-rule py-6 sm:grid-cols-[70px_230px_1fr] sm:gap-7"><span className="font-mono text-[10px] text-[#5f5f5f]">{n}</span><h3 className="text-[18px] font-normal tracking-[-.02em]">{t}</h3><p className="booth-copy max-w-[600px] text-[13px] leading-6">{c}</p></article>)}</div></div></section>

<section className="border-b booth-rule py-16 sm:py-24"><div className="mx-auto grid w-[min(1200px,calc(100%-36px))] gap-12 lg:grid-cols-[.62fr_1.38fr]"><div><p className="booth-kicker">08 / Questions before a rebuild</p><h2 className="booth-display mt-5 text-[clamp(34px,6vw,50px)] leading-[1.03]">The sensible objections are worth answering properly.</h2><p className="booth-copy mt-5 text-[14px] leading-7">A commercial insurance website should support the brokerage’s real sales process, not force it into a generic digital funnel.</p></div><div><BrokerFAQ/></div></div></section>

<section className="bg-[#080808] py-16 sm:py-24"><div className="mx-auto w-[min(1200px,calc(100%-36px))]"><div className="grid gap-8 border-y booth-rule py-12 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="booth-kicker">Not sure whether a rebuild is justified?</p><h2 className="booth-display mt-5 max-w-[760px] text-[clamp(38px,8vw,64px)] leading-[1]">Start with your current website.</h2><p className="booth-copy mt-5 max-w-[650px] text-[15px] leading-7">We will assess what is working, what is weakening trust and whether the right answer is to keep it, improve it or rebuild it.</p><p className="mt-3 max-w-[620px] text-[11px] leading-6 text-[#666]">The audit looks at positioning, credibility, buyer journey and enquiry flow before recommending what should happen next.</p></div><Link href="/website-audit" className="booth-primary inline-flex items-center justify-center whitespace-nowrap">Request Website Audit<ArrowUpRight className="ml-2 h-4 w-4"/></Link></div></div></section><SiteFooter/></main>}
