import { ArrowRight } from 'lucide-react'
import Link from 'next/link'
import BrokerFAQ from '../components/BrokerFAQ'
import SiteFooter from '../components/SiteFooter'
import SiteHeader from '../components/SiteHeader'

const problems=[['The brokerage has grown. The website hasn’t.','The team, client base and capability have moved forward, but the site still represents an earlier version of the business.'],['Referrals still check the website.','A recommendation may open the door, but prospects still use the site to decide whether the brokerage feels credible and relevant.'],['Your expertise has become a product list.','Lines such as liability, property and fleet say what you can place. They do not show why a commercial client should choose your brokerage.'],['Competitors can look more established online.','A less experienced firm can appear like the safer choice when its positioning, people and sector expertise are easier to understand.']]
const framework=[['POSITION','Make it immediately clear who the brokerage serves and why it is worth choosing.'],['PROVE','Demonstrate sector knowledge, broker expertise and legitimate evidence.'],['REASSURE','Use people, process, credibility and appropriate regulatory information to reduce uncertainty.'],['CONVERT','Move appropriate commercial prospects toward the right broker conversation.']]
const process=[['01','Understand the brokerage','Clients, specialisms, team, sales process and positioning.'],['02','Audit the existing website','Messaging, credibility, services, sectors and enquiry journey.'],['03','Map the buyer journey','How a prospect moves from referral or introduction to broker conversation.'],['04','Design and build','Messaging, structure, visual design and development.'],['05','Review and launch','Responsive QA, forms, journeys, regulatory presentation, SEO foundations and final checks.']]
function Heading({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}){return <div className="max-w-[820px]"><p className="bm-eyebrow">{eyebrow}</p><h2 className="bm-heading mt-4">{title}</h2>{copy&&<p className="bm-copy mt-5 max-w-[720px]">{copy}</p>}</div>}

export default function Page(){return <main className="bm-page"><SiteHeader/>
<section className="bm-hero"><div className="bm-shell bm-hero-inner"><div className="bm-hero-copy"><p className="bm-eyebrow">Websites for Commercial Insurance Brokers</p><h1 className="bm-display mt-5"><span className="text-[#7fee64]">Your brokerage has earned its reputation.</span> Does your website reflect it?</h1><p className="bm-copy">We design conversion-focused websites for established commercial insurance brokers that need to look credible, explain their expertise clearly and turn more serious prospects into broker conversations.</p><p className="bm-hero-support">Your brokerage already earns trust offline. Your website should reinforce it online.</p><div className="bm-actions"><Link href="/website-audit" className="bm-primary">Request Brokerage Website Audit<ArrowRight className="ml-2.5 h-4 w-4"/></Link><Link href="/work/northstead-commercial-risk" className="bm-secondary">See Commercial Insurance Concept</Link></div></div><div className="bm-cube-stage" aria-hidden="true"><div className="bm-orbit"/><div className="bm-cube"/><div className="bm-status"><i/>BROKERAGE / SIGNAL ONLINE</div></div></div></section>

<section className="bm-section bm-section-alt"><div className="bm-shell-narrow"><Heading eyebrow="Problem recognition" title="A strong brokerage can still look ordinary online." copy="The problem is rarely that the brokerage lacks substance. It is that the website does not make that substance obvious to a busy commercial buyer."/><div className="bm-problem-grid">{problems.map(([title,copy],i)=><article key={title} className="bm-problem"><span className="bm-num">0{i+1}</span><div><h3 className="bm-card-title text-[20px]">{title}</h3><p className="bm-copy-sm mt-3">{copy}</p></div></article>)}</div><Link href="/websites" className="bm-link mt-7">See How We Approach Broker Websites<ArrowRight className="h-4 w-4"/></Link></div></section>

<section className="bm-section"><div className="bm-shell-narrow"><Heading eyebrow="Referral validation" title="The referral gets you considered. The website helps validate the recommendation." copy="Referrals, introducers, networking and outbound can create trust before a prospect lands on the site. The website should preserve that confidence and make speaking to a broker feel like the obvious next step."/><div className="bm-pipeline">{['Referral / Introduction','Website Check','Confidence','Broker Conversation'].map((node,i)=><div key={node} className={`bm-node ${i===1?'bm-node-active':''}`}>{node}</div>)}</div></div></section>

<section className="bm-section bm-section-alt"><div className="bm-shell-narrow"><Heading eyebrow="A better broker website" title="Move beyond generic insurance language."/><div className="bm-compare"><div className="bm-compare-head"><span>Typical</span><span>Better</span></div>{[['“Tailored insurance solutions for businesses of all sizes.”','Clear positioning around the businesses and sectors the brokerage understands.'],['Insurance product catalogue.','Buyer problems, sectors, expertise and connected commercial risks.'],['“Get a Quote.”','Create an appropriate broker conversation.']].map(([a,b])=><div key={a} className="bm-compare-row"><p className="bm-copy-sm">{a}</p><p className="bm-copy-sm">{b}</p></div>)}</div><Link href="/work/northstead-commercial-risk" className="bm-link mt-7">See the Northstead Concept<ArrowRight className="h-4 w-4"/></Link></div></section>

<section className="bm-section"><div className="bm-shell-narrow"><Heading eyebrow="Booth Brokerage Website Framework" title="Position. Prove. Reassure. Convert." copy="A broker website should make the right buyer understand the fit, trust the people behind the advice and know what to do next."/><div className="bm-framework">{framework.map(([t,c],i)=><article key={t}><span className="bm-num">0{i+1}</span><h3 className="bm-card-title mt-6 text-[24px] tracking-[.03em]">{t}</h3><p className="bm-copy-sm mt-3 max-w-[440px]">{c}</p></article>)}</div></div></section>

<section className="bm-section bm-section-alt"><div className="bm-shell-narrow grid gap-8 lg:grid-cols-2"><div><Heading eyebrow="Commercial insurance expertise" title="We understand how commercial insurance is actually sold."/><p className="bm-copy-sm mt-6">Commercial insurance is relationship-led. Referrals matter. Introducers matter. Renewals matter. Prospects often describe operational problems rather than policy terminology, and different sectors bring different exposures.</p><p className="bm-copy-sm mt-4">That means a good website should support the people inside the brokerage and attract appropriate conversations, not simply chase the largest possible number of quote forms.</p></div><div className="bm-card"><p className="bm-eyebrow">People are part of the proposition</p><h3 className="bm-card-title mt-4 text-[30px] leading-[1.08] tracking-[-.025em]">Experienced brokers should not be hidden behind stock imagery.</h3><p className="bm-copy-sm mt-5">Broker profiles, sector knowledge, real process and visible expertise help a commercial buyer understand who they may actually speak to. The people inside the brokerage are an asset.</p></div></div></section>

<section className="bm-section"><div className="bm-shell-narrow"><div className="bm-proof-grid grid gap-12 lg:grid-cols-[.82fr_1.18fr] lg:items-center"><div><p className="bm-eyebrow">Flagship proof</p><h2 className="bm-heading mt-4">Northstead Commercial Risk</h2><p className="mt-3 text-[12px] font-semibold uppercase tracking-[.16em] text-[#8cab87]">Independent Commercial Insurance Brokerage Concept</p><p className="bm-copy-sm mt-6">The concept starts with a familiar problem: broker websites often lead with insurance products and generic promises. Northstead instead positions the brokerage around understanding commercial risk and the buyer’s operation.</p><div className="mt-6 space-y-3 text-[14px] leading-6 text-[#8cab87]"><p><strong className="text-[#ddffdc]">Buyer:</strong> established business owners and managing directors.</p><p><strong className="text-[#ddffdc]">Conversion:</strong> move away from a generic quote journey toward a broker-led commercial conversation.</p></div><p className="mt-5 text-[11px] leading-5 text-[#677d64]">Independent concept work. Not a commissioned client project.</p><Link href="/work/northstead-commercial-risk" className="bm-primary mt-6">Explore the Commercial Insurance Concept<ArrowRight className="ml-2 h-4 w-4"/></Link></div><div className="bm-terminal"><div className="bm-terminal-bar"><span className="bm-terminal-dot"/><span className="bm-terminal-dot"/><span className="bm-terminal-dot"/><span className="bm-terminal-label">BOOTH / CASE_STUDY / NORTHSTEAD</span></div><img src="/work/northstead.png" alt="Northstead Commercial Risk concept homepage"/></div></div><div className="bm-proof-meta"><div className="bm-card"><p className="bm-eyebrow">Execution range</p><h3 className="bm-card-title mt-3 text-[20px]">Purple Door Leeds</h3><p className="bm-copy-sm mt-2">Secondary proof of visual execution outside the brokerage specialism.</p></div><div className="bm-card"><p className="bm-eyebrow">Execution range</p><h3 className="bm-card-title mt-3 text-[20px]">Graft Haus Gym</h3><p className="bm-copy-sm mt-2">Secondary proof of responsive, conversion-led execution.</p></div></div></div></section>

<section className="bm-section bm-section-alt"><div className="bm-shell-narrow"><Heading eyebrow="How it works" title="A manageable process for a busy brokerage MD."/><div className="bm-process">{process.map(([n,t,c])=><article key={n}><span className="bm-num">{n}</span><h3 className="bm-card-title mt-4 text-[18px]">{t}</h3><p className="bm-copy-sm mt-3">{c}</p></article>)}</div><Link href="/how-it-works" className="bm-link mt-8">Explore Our Process<ArrowRight className="h-4 w-4"/></Link></div></section>

<section className="bm-section"><div className="bm-shell-narrow grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div className="lg:sticky lg:top-24 lg:self-start"><p className="bm-eyebrow">Questions before a rebuild</p><h2 className="bm-heading mt-4">The sensible objections are worth answering properly.</h2><p className="bm-copy-sm mt-5">A commercial insurance website should support the brokerage’s real sales process, not force it into a generic digital funnel.</p></div><BrokerFAQ/></div></section>

<section className="bm-section bm-cta bm-section-alt"><div className="bm-shell-narrow bm-cta-inner"><p className="bm-eyebrow">Still deciding whether a rebuild is justified?</p><h2 className="bm-heading mt-4">Start with your current website.</h2><p className="bm-copy mx-auto mt-5 max-w-[620px]">We will assess what is working, what is weakening trust and whether the right answer is to keep it, improve it or rebuild it.</p><Link href="/website-audit" className="bm-primary mt-7">Request Brokerage Website Audit<ArrowRight className="ml-2.5 h-4 w-4"/></Link></div></section><SiteFooter/></main>}
