'use client'
import { ChevronDown } from 'lucide-react'
import { useState } from 'react'
const items=[
["I don't know what I need automated. Where do we start?","You do not need to arrive with a solution. We start by understanding how work currently moves through the business, where time is being lost and which repetitive tasks or bottlenecks are worth investigating."],
["What exactly is AI automation?","It is the use of software and AI inside a repeatable business process. Instead of somebody manually prompting AI each time, the system can receive information, interpret it, move data between approved tools, prepare an action and involve a person where judgement is required."],
["We already use ChatGPT. What's different?","Using ChatGPT is usually a manual interaction. Automation connects AI to a defined workflow so useful work can move between the systems and people involved without somebody starting from scratch every time."],
["Will AI replace our staff?","That is not the objective. We look first for repetitive work that consumes your team's time without needing their judgement, relationships or experience. People stay involved where they add value."],
["What happens if the AI makes a mistake?","AI can make mistakes, so the workflow should be designed around the risk involved. That can include validation, restricted actions, human approval, confidence thresholds and escalation when the system is uncertain."],
["What happens to our business or customer data?","Data handling depends on the systems and providers required for the workflow. We consider what information is actually needed, how it moves between systems and what access should be limited before implementation."],
["Will this work with the software we already use?","We check that before proposing the implementation. Some systems provide APIs or existing integrations, some require alternative approaches, and some are not sensible to automate. That technical reality should be known before a larger build is agreed."],
["How do we know automation will actually be worth it?","We identify the current bottleneck first, then consider the size of the opportunity, how quickly value could appear, and the cost and complexity of implementation. If the commercial case is weak, it should not be the first thing we build."],
["How long does implementation take?","It depends on the workflow, systems, integrations, testing and approvals involved. We define the scope before the full implementation so you know what is being built and what the important dependencies are."],
["Do we need to replace all our existing systems?","Usually the starting point is to understand the tools you already use. Where practical, automation should work around useful existing systems rather than creating a technology replacement project without a reason."],
["What happens after you've built it?","You can choose a handover model where the agreed system is built, tested and documented, or an ongoing model where Booth continues supporting and improving the implementation."],
["What does it cost?","Cost depends on the process, integrations and complexity. We first identify whether the opportunity is commercially worth solving, then scope the implementation before you commit to the build."]
]
export default function AutomationFAQ(){const[open,setOpen]=useState<number|null>(0);return <div className="divide-y divide-[#242424] border-y border-[#242424]">{items.map(([q,a],i)=>{const active=open===i;const id=`automation-faq-${i}`;return <div key={q}><button onClick={()=>setOpen(active?null:i)} aria-expanded={active} aria-controls={id} className="flex min-h-[66px] w-full items-center justify-between gap-4 py-3 text-left"><span className="text-[14px] font-medium text-[#e8e8e7] sm:text-[15px]">{q}</span><ChevronDown className={`h-4 w-4 shrink-0 text-[#8d8e94] transition-transform duration-200 ${active?'rotate-180':''}`}/></button><div id={id} className={`grid transition-all duration-200 ${active?'grid-rows-[1fr] pb-5':'grid-rows-[0fr]'}`}><div className="overflow-hidden"><p className="max-w-[720px] text-[13px] leading-6 text-[#85868c]">{a}</p></div></div></div>})}</div>}