'use client'
import {useState} from 'react'
const gbp=(v:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(v)
export default function AutomationROICalculator(){
 const [people,setPeople]=useState(10),[hours,setHours]=useState(5),[cost,setCost]=useState(25),[share,setShare]=useState(30),[weeks,setWeeks]=useState(46)
 const capacity=people*hours*weeks*share/100
 const controls=[{name:'Employees involved in the process',value:people,set:setPeople,min:1,max:100,unit:'people'},{name:'Manual hours per employee per week',value:hours,set:setHours,min:1,max:30,unit:'hours'},{name:'Estimated hourly employment cost',value:cost,set:setCost,min:12,max:80,unit:'£'},{name:'Potentially automatable share',value:share,set:setShare,min:5,max:80,unit:'%'},{name:'Working weeks per year',value:weeks,set:setWeeks,min:1,max:52,unit:'weeks'}]
 return <div className="booth-panel bg-[#0b0b0b] p-5 sm:p-8"><div className="grid gap-9 lg:grid-cols-2"><div className="space-y-6">{controls.map(item=><label key={item.name} className="block"><span className="mb-3 flex flex-wrap items-center justify-between gap-2 text-[13px] text-[#bbb]"><span>{item.name}</span><strong className="font-medium text-white">{item.unit==='£'?'£':''}{item.value}{item.unit==='%'?'%':''}</strong></span><input className="w-full accent-[#d92f3c]" type="range" min={item.min} max={item.max} value={item.value} onChange={e=>item.set(Number(e.target.value))}/></label>)}</div><div className="flex flex-col justify-center gap-4"><div className="border-b booth-rule pb-5"><p className="booth-kicker">Illustrative hours potentially recovered / year</p><p className="mt-3 text-[clamp(36px,5vw,64px)] tracking-[-.05em]">{Math.round(capacity).toLocaleString('en-GB')} <span className="text-[16px] text-[#888]">hours</span></p></div><div><p className="booth-kicker">Equivalent annual capacity value</p><p className="mt-3 text-[clamp(36px,5vw,64px)] tracking-[-.05em]">{gbp(capacity*cost)}</p></div><p className="text-[11px] leading-6 text-[#888]">Illustrative scenario using an editable working-weeks assumption, not a forecast or guaranteed cash saving. Real outcomes depend on process suitability, implementation, human review and adoption. Recovered time does not necessarily reduce payroll expenditure. Software and implementation costs are not deducted.</p></div></div></div>
}
