'use client'
import { useState } from 'react'
type Scenario={label:string;input:string;valid:boolean;classification:string;route:string;review:string;result:string}
const scenarios:Scenario[]=[
 {label:'Valid enquiry',input:'Name: Alex; Email: alex@example.test; Request: Please quote for a delivery.',valid:true,classification:'New sales enquiry',route:'Sales review queue',review:'Person checks suitability before responding',result:'Prepared for human follow-up'},
 {label:'Missing details',input:'Name: Alex; Email: missing; Request: Call me.',valid:false,classification:'Validation failed',route:'No external action',review:'Ask the submitter for a valid email address',result:'Request not processed'},
 {label:'Ambiguous request',input:'Name: Morgan; Email: morgan@example.test; Request: Need help with an order or maybe a quote.',valid:true,classification:'Uncertain intent',route:'General enquiry queue',review:'Human determines the correct destination',result:'Flagged for manual triage'},
 {label:'Duplicate request',input:'Same submission identifier as a previously accepted enquiry.',valid:true,classification:'Potential retry',route:'Original enquiry reference',review:'No duplicate action should be created',result:'Existing result reused'},
 {label:'Delivery failure',input:'Name: Casey; Email: casey@example.test; Request: Please contact me.',valid:true,classification:'New enquiry',route:'Notification queue',review:'Administrator reviews failed delivery',result:'Enquiry retained; notification marked for retry'}
]
export default function WorkflowSimulation(){const [index,setIndex]=useState(0);const [ran,setRan]=useState(false);const s=scenarios[index];return <section aria-labelledby="simulation-title" className="booth-panel p-5 sm:p-8"><p className="booth-kicker">Interactive synthetic demonstration</p><h2 id="simulation-title" className="booth-display mt-3 text-[28px] sm:text-[38px]">Explore a controlled enquiry workflow.</h2><p className="booth-copy mt-3 text-[13px] leading-6">Choose a fictional scenario and run the example. This does not contact an AI model, send messages, process real enquiries or access the CRM.</p><label htmlFor="scenario" className="mt-7 block text-[13px] text-[#ccc]">Scenario</label><select id="scenario" value={index} onChange={e=>{setIndex(Number(e.target.value));setRan(false)}} className="mt-2 min-h-12 w-full rounded-md border border-[#444] bg-[#111] px-3 text-white">{scenarios.map((x,i)=><option value={i} key={x.label}>{x.label}</option>)}</select><div className="mt-5 rounded-md border border-[#333] bg-[#080808] p-4"><p className="booth-kicker">Example input</p><p className="mt-3 whitespace-pre-wrap break-words text-[13px] leading-6 text-[#bbb]">{s.input}</p></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={()=>setRan(true)} className="booth-primary min-h-11 px-5">Run example</button><button type="button" onClick={()=>setRan(false)} className="min-h-11 rounded-full border border-[#555] px-5 text-[13px] text-white">Reset</button></div><div aria-live="polite" aria-atomic="true" className="mt-6">{ran?<div className="grid gap-3 sm:grid-cols-2">{[['Validation',s.valid?'Passed':'Needs correction'],['Classification',s.classification],['Routing',s.route],['Human review',s.review],['Illustrative result',s.result]].map(([a,b])=><div key={a} className="rounded-md border border-[#333] p-4"><p className="booth-kicker">{a}</p><p className="mt-3 text-[13px] leading-6 text-white">{b}</p></div>)}</div>:<p className="text-[13px] text-[#888]">No example has been run yet.</p>}</div></section>}
