import Link from 'next/link'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import AdminShell from '@/components/admin/AdminShell'
import { deleteLead, getLeadActivity, getLeadById, updateLead, LeadStatus } from '@/lib/leads'

export const dynamic='force-dynamic'
export const revalidate=0
const statuses:LeadStatus[]=['NEW','CONTACTED','QUALIFIED','BOOKED','CLOSED_WON','CLOSED_LOST'];const scores=['','Low','Medium','High','Very High']
export default async function LeadPage({params}:{params:Promise<{id:string}>}){const {id}=await params;let lead=null;try{lead=await getLeadById(id)}catch{};if(!lead)return <AdminShell section="Leads"><div className="mx-auto max-w-4xl rounded-[18px] border border-white/[.075] bg-[#0d0f10] p-10 text-center"><h1 className="text-xl font-semibold">Lead unavailable</h1><Link href="/admin/leads" className="mt-5 inline-block text-[11px] text-[#d8cbb7]">Back to leads</Link></div></AdminShell>;const activity=await getLeadActivity(id)
 async function save(formData:FormData){'use server';const status=String(formData.get('status')||'') as LeadStatus,opportunityScore=String(formData.get('opportunityScore')||'');if(!statuses.includes(status)||!scores.includes(opportunityScore))return;await updateLead(id,{status,websiteUrl:String(formData.get('websiteUrl')||'').trim().slice(0,500),opportunityScore,notes:String(formData.get('notes')||'').trim().slice(0,6000)});revalidatePath('/admin');revalidatePath('/admin/leads');revalidatePath(`/admin/leads/${id}`)}
 async function remove(){'use server';await deleteLead(id);revalidatePath('/admin');revalidatePath('/admin/leads');redirect('/admin/leads')}
 const field='mt-2 w-full rounded-xl border border-white/[.08] bg-[#090a0b] p-3 text-[12px] text-white outline-none focus:border-[#d8cbb7]/35'
 return <AdminShell section="Leads"><div className="mx-auto max-w-[1050px]"><Link href="/admin/leads" className="text-[10px] text-[#77787e] hover:text-white">← Back to leads</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-5"><div><span className="rounded-full border border-[#d92f3c]/15 bg-[#190f11] px-2.5 py-1 text-[8px] uppercase tracking-[.1em] text-[#c9a3a7]">{(lead.enquiryType||'WEBSITE_AUDIT').replaceAll('_',' ')}</span><h1 className="mt-4 text-[36px] font-semibold tracking-[-.05em]">{lead.company}</h1><p className="mt-2 text-[11px] text-[#77787e]">{lead.name} · {lead.email}</p><div className="mt-4 flex flex-wrap gap-2"><a href={`mailto:${lead.email}`} className="rounded-lg border border-white/[.08] px-3 py-2 text-[10px] text-[#d7d6d6] hover:bg-white/[.04]">Email contact</a>{lead.websiteUrl&&<a href={lead.websiteUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-white/[.08] px-3 py-2 text-[10px] text-[#d7d6d6] hover:bg-white/[.04]">Open website ↗</a>}</div></div><p className="text-[9px] text-[#55565b]">Submitted {new Date(lead.createdAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</p></div>
 <div className="mt-7 grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]"><div><form action={save} className="rounded-[18px] border border-white/[.075] bg-[#0d0f10] p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-[10px] text-[#85868c]">Lead status<select name="status" defaultValue={lead.status} className={field}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-[10px] text-[#85868c]">Website URL<input name="websiteUrl" type="url" defaultValue={lead.websiteUrl||''} placeholder="https://" className={field}/></label></div>{lead.challenge&&<div className="mt-5 border-t border-white/[.06] pt-5"><p className="text-[9px] font-bold uppercase tracking-[.13em] text-[#55565b]">What they need</p><p className="mt-2 whitespace-pre-line text-[11px] leading-6 text-[#8b8c92]">{lead.challenge}</p></div>}<label className="mt-5 block text-[10px] text-[#85868c]">Internal notes<textarea name="notes" defaultValue={lead.notes||''} rows={6} className={`${field} resize-y`}/></label><div className="mt-5 flex justify-end"><button className="rounded-xl bg-[#efe3cf] px-5 py-3 text-[11px] font-semibold text-[#151515]">Save lead</button></div></form><form action={remove} className="mt-4 rounded-[18px] border border-[#d92f3c]/20 bg-[#190f11]/40 p-5"><p className="text-[11px] font-semibold text-[#e4c7ca]">Temporary testing control</p><p className="mt-1 text-[9px] leading-5 text-[#8f686d]">Deletes this lead permanently. This button will be removed after your test.</p><button className="mt-4 rounded-xl border border-[#d92f3c]/35 bg-[#d92f3c]/10 px-4 py-2.5 text-[10px] font-semibold text-[#efb7bd] hover:bg-[#d92f3c]/20">Delete this test lead</button></form></div><aside className="h-fit rounded-[18px] border border-white/[.075] bg-[#0d0f10] p-5"><h2 className="text-[13px] font-semibold">Activity</h2><div className="mt-5 space-y-4">{activity.length?activity.map(item=><div key={item.id} className="border-l border-white/[.09] pl-4"><p className="text-[10px] leading-5 text-[#c9c9c7]">{item.summary}</p><p className="mt-1 text-[8px] text-[#505156]">{new Date(item.createdAt).toLocaleString('en-GB')}</p></div>):<p className="text-[9px] leading-5 text-[#5e5f65]">No activity recorded yet.</p>}</div></aside></div></div></AdminShell>}
