import { ArrowRight, Check } from 'lucide-react'
import Link from 'next/link'
import SiteFooter from '../../components/SiteFooter'
import SiteHeader from '../../components/SiteHeader'
const steps=[['01','Understand the business','Get clear on what you sell, who buys, how work is won and what has changed since the current website was built.'],['02','Audit what exists','Review the current site for positioning, trust, proof, usability and the parts that are still worth keeping.'],['03','Agree the direction','Define the pages, messaging and buyer journey before design work starts. You know what is being built and why.'],['04','Design and build','Turn the agreed direction into a fast, responsive website without making the owner manage every implementation detail.'],['05','Review and launch','Test the important journeys, make final refinements and launch once the website represents the business properly.']]
export default function HowItWorksPage(){return <main className="min-h-screen bg-[#090a0b] text-[#f4f4f3]"><SiteHeader/>
<section className="border-b border-white/[.055] py-12 sm:py-16"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><p className="text-[10px] font-extrabold uppercase tracking-[.24em] text-[#d8cbb7]">How It Works</p><h1 className="mt-4 max-w-[850px] text-[clamp(40px,9vw,62px)] font-semibold leading-[1.01] tracking-[-.055em]">A website rebuild should not become another job for the owner.</h1><p className="mt-5 max-w-[730px] text-[15px] leading-7 text-[#929399]">The process is structured around a small number of useful decisions. We understand the business first, agree the direction, then carry the work through.</p></div></section>
<section className="border-b border-white/[.055] bg-[#0b0d0e] py-10 sm:py-14"><div className="mx-auto w-[min(1080px,calc(100%-28px))]"><div className="overflow-hidden rounded-[18px] border border-white/[.07] bg-white/[.025]">{steps.map(([n,t,c])=><div key={n} className="grid grid-cols-[42px_1fr] gap-3 border-b border-white/[.07] p-5 last:border-0 sm:grid-cols-[60px_220px_1fr] sm:items-center"><span className="text-[9px] font-bold tracking-[.16em] text-[#77787e]">{n}</span><div><p className="text-[16px] font-semibold">{t}</p><p className="mt-1 text-[13px] leading-6 text-[#808187] sm:hidden">{c}</p></div><p className="hidden text-[13px] leading-6 text-[#808187] sm:block">{c}</p></div>)}</div></div></section>
<section className="border-b border-white/[.055] py-10 sm:py-14"><div className="mx-auto grid w-[min(1080px,calc(100%-28px))] gap-5 lg:grid-cols-2"><div className="rounded-[18px] border border-white/[.07] bg-[#0d0f10] p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#cfc2ae]">What we need from you</p><div className="mt-4 space-y-3">{['Context on the business and customers','Access to useful existing brand and website material','Clear feedback at agreed decision points','The people needed to approve the final direction'].map(x=><div key={x} className="flex items-start gap-2.5 text-[13px] leading-6 text-[#98999f]"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-[#d8cbb7]"/>{x}</div>)}</div></div><div className="rounded-[18px] border border-[#d92f3c]/18 bg-[#190f11]/42 p-5"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#cfc2ae]">What you should not have to do</p><div className="mt-4 space-y-3">{['Write a complete redesign brief yourself','Learn web design terminology','Approve endless cosmetic decisions','Replace useful content just because it is old','Manage the technical build'].map(x=><div key={x} className="flex items-start gap-2.5 text-[13px] leading-6 text-[#a49598]"><Check className="mt-1 h-3.5 w-3.5 shrink-0 text-[#d8cbb7]"/>{x}</div>)}</div></div></div></section>
<section className="border-b border-white/[.055] bg-[#0b0d0e] py-10 sm:py-14"><div className="mx-auto grid w-[min(1080px,calc(100%-28px))] gap-5 lg:grid-cols-2"><div><p className="text-[10px] font-extrabold uppercase tracking-[.22em] text-[#d8cbb7]">Keep what earned its place</p><h2 className="mt-4 text-[clamp(30px,7vw,44px)] font-semibold tracking-[-.045em]">A rebuild does not mean starting the business again from zero.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">Existing search equity, strong content, recognisable brand assets and useful pages can all carry forward. Change should have a commercial reason.</p></div><div className="rounded-[17px] border border-white/[.07] bg-[#0d0f10] p-5"><p className="text-[13px] leading-7 text-[#999aa0]">The goal is simple: preserve what already supports the business, fix what no longer represents it, and make the finished website easier for a serious buyer to trust and act on.</p></div></div></section>
<section className="py-12 text-center sm:py-16"><div className="mx-auto w-[min(760px,calc(100%-28px))]"><h2 className="text-[clamp(34px,7.5vw,50px)] font-semibold leading-[1.04] tracking-[-.048em]">Start with the current website, not a redesign brief.</h2><p className="mt-4 text-[14px] leading-7 text-[#8d8e94]">We will show you what is worth keeping, what is weakening confidence and whether a rebuild is actually justified.</p><Link href="/website-audit" className="mt-6 inline-flex min-h-[50px] items-center justify-center rounded-lg bg-[#efe3cf] px-5 text-[13px] font-semibold text-[#151515]">Request Website Audit<ArrowRight className="ml-2.5 h-4 w-4"/></Link></div></section><SiteFooter/></main>}
