'use client'
import { ArrowRight, Check } from 'lucide-react'
import { FormEvent,useState } from 'react'
import SiteFooter from '../../components/SiteFooter'
import SiteHeader from '../../components/SiteHeader'
const auditItems=['Positioning','Credibility','Buyer journey','Conversion','Mobile experience']
export default function WebsiteAuditPage(){const[submitted,setSubmitted]=useState(false);const[submitting,setSubmitting]=useState(false);const[submitError,setSubmitError]=useState('');const[errors,setErrors]=useState<Record<string,string>>({});
const handleSubmit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSubmitError('');const el=event.currentTarget;const form=new FormData(el);const next:Record<string,string>={};for(const field of ['name','email','company','website'])if(!String(form.get(field)||'').trim())next[field]='Required';const email=String(form.get('email')||'');if(email&&!/^\S+@\S+\.\S+$/.test(email))next.email='Enter a valid email';setErrors(next);if(Object.keys(next).length)return;setSubmitting(true);try{const response=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:String(form.get('name')||'').trim(),email:email.trim(),company:String(form.get('company')||'').trim(),websiteUrl:String(form.get('website')||'').trim(),industry:String(form.get('industry')||'').trim(),teamSize:'',challenge:String(form.get('notes')||'').trim(),websiteCompany:String(form.get('websiteCompany')||'').trim(),enquiryType:'WEBSITE_AUDIT'})});const data=await response.json().catch(()=>({})) as{error?:string};if(!response.ok)throw new Error(data.error||'We could not submit your request. Please try again.');el.reset();setSubmitted(true)}catch(error){setSubmitError(error instanceof Error?error.message:'We could not submit your request. Please try again.')}finally{setSubmitting(false)}};
return <main className="booth-public min-h-screen"><SiteHeader/>
<section className="border-b booth-rule bg-[#080808]"><div className="booth-container py-12 sm:py-16 lg:py-20"><p className="booth-kicker">Website Audit</p><h1 className="booth-display booth-mobile-heading mt-5 max-w-[880px]">Has your website fallen behind the brokerage?</h1><p className="booth-copy booth-mobile-copy mt-5 max-w-[720px]">We review the current site from the perspective of a serious commercial buyer and identify what is worth keeping, what may be weakening confidence and whether a rebuild is justified.</p></div></section>
<section className="booth-section"><div className="booth-container grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:gap-16"><aside><p className="booth-kicker">What we review</p><div className="mt-5 border-t booth-rule">{auditItems.map((item,i)=><div key={item} className="grid grid-cols-[34px_1fr] border-b booth-rule py-4"><span className="font-mono text-[9px] text-[#626262]">0{i+1}</span><span className="text-[13px] text-[#bbb]">{item}</span></div>)}</div><p className="booth-copy mt-6 text-[13px] leading-6">The audit is diagnostic. If the right answer is to keep the current site or make targeted improvements rather than rebuild it, that should be the recommendation.</p></aside><div className="border-t booth-rule pt-6 lg:border-l lg:border-t-0 lg:pl-10"><p className="booth-kicker">Request Website Audit</p>{submitted?<div className="py-10"><Check className="h-5 w-5 text-white"/><h2 className="booth-display mt-5 text-[28px]">Thanks. Your audit request has been received.</h2><p className="booth-copy mt-3 text-[13px] leading-6">We will review the website and identify the most useful next steps.</p></div>:<form onSubmit={handleSubmit} noValidate className="mt-6 grid gap-5 sm:grid-cols-2"><input name="websiteCompany" tabIndex={-1} autoComplete="off" aria-hidden="true" className="absolute left-[-9999px] h-px w-px opacity-0"/><Field label="Full Name" name="name" error={errors.name}/><Field label="Business Email" name="email" type="email" error={errors.email}/><Field label="Company" name="company" error={errors.company}/><Field label="Current Website URL" name="website" inputMode="url" placeholder="example.com" error={errors.website}/><Field label="Industry" name="industry" optional/><div className="sm:col-span-2"><label htmlFor="notes" className="mb-2 block text-[12px] text-[#cfcfcf]">Anything we should know? <span className="text-[#666]">Optional</span></label><textarea id="notes" name="notes" rows={4} placeholder="For example: the brokerage has changed, the site feels dated, or prospects struggle to understand a service." className="w-full px-4 py-3 text-[16px] placeholder:text-[#5f5f5f]"/></div><div className="sm:col-span-2"><button disabled={submitting} className="booth-primary flex w-full items-center justify-center disabled:opacity-60">{submitting?'Submitting...':'Request Website Audit'}{!submitting&&<ArrowRight className="ml-2 h-4 w-4"/>}</button>{submitError&&<p className="mt-3 text-[12px] text-[#d1a3a8]" role="alert">{submitError}</p>}<p className="mt-3 text-[10px] leading-5 text-[#666]">Your details are used to review your website and respond to your audit request.</p></div></form>}</div></div></section><SiteFooter/></main>}
function Field({label,name,type='text',inputMode,placeholder,error,optional=false}:{label:string;name:string;type?:string;inputMode?:'url'|'email'|'text'|'search'|'tel'|'none'|'numeric'|'decimal';placeholder?:string;error?:string;optional?:boolean}){return <div><label htmlFor={name} className="mb-2 block text-[12px] text-[#cfcfcf]">{label} {optional&&<span className="text-[#666]">Optional</span>}</label><input id={name} name={name} type={type} inputMode={inputMode} placeholder={placeholder} aria-invalid={Boolean(error)} aria-describedby={error?`${name}-error`:undefined} className="w-full px-4 py-3 text-[16px] placeholder:text-[#5f5f5f]"/>{error&&<p id={`${name}-error`} className="mt-1.5 text-[11px] text-[#d1a3a8]">{error}</p>}</div>}
