import Link from 'next/link'
import { Download, ExternalLink, LayoutDashboard, LogOut, Menu, Search, Users } from 'lucide-react'
import type { ReactNode } from 'react'

const nav=[
 {href:'/admin',label:'Overview',icon:LayoutDashboard},
 {href:'/admin/leads',label:'Leads',icon:Users},
]
export default function AdminShell({children,section='Overview'}:{children:ReactNode;section?:string}){
 return <div className="min-h-screen bg-[#090a0b] text-[#f4f4f3] lg:grid lg:grid-cols-[245px_1fr]">
  <aside className="hidden min-h-screen border-r border-white/[.07] bg-[#0b0d0e] lg:sticky lg:top-0 lg:flex lg:h-screen lg:flex-col"><div className="border-b border-white/[.07] px-6 py-6"><img src="/booth-marketing-logo.png" alt="Booth Marketing" className="w-[150px]"/><p className="mt-3 text-[9px] font-bold uppercase tracking-[.22em] text-[#66676d]">Website leads</p></div><nav className="flex-1 space-y-1 p-3">{nav.map(item=>{const Icon=item.icon,active=section===item.label;return <Link key={item.href} href={item.href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-[12px] font-medium transition ${active?'border border-[#efe3cf]/10 bg-[#efe3cf] text-[#151515]':'text-[#8b8c92] hover:bg-white/[.035] hover:text-white'}`}><Icon className="h-4 w-4"/>{item.label}</Link>})}</nav><div className="space-y-1 border-t border-white/[.07] p-3"><Link href="/admin/leads" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[12px] text-[#7d7e84] hover:bg-white/[.035] hover:text-white"><Search className="h-4 w-4"/>Search leads</Link><a href="/api/admin/leads/export" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[12px] text-[#7d7e84] hover:bg-white/[.035] hover:text-white"><Download className="h-4 w-4"/>Export CSV</a><Link href="/" target="_blank" className="flex items-center gap-3 rounded-xl px-3 py-3 text-[12px] text-[#7d7e84] hover:bg-white/[.035] hover:text-white"><ExternalLink className="h-4 w-4"/>View website</Link><form action="/api/admin/logout" method="post"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-[12px] text-[#7d7e84] hover:bg-white/[.035] hover:text-white"><LogOut className="h-4 w-4"/>Log out</button></form><p className="px-3 pt-3 text-[9px] uppercase tracking-[.16em] text-[#4f5055]">Private lead workspace</p></div></aside>
  <div className="min-w-0"><header className="sticky top-0 z-30 flex min-h-[62px] items-center justify-between border-b border-white/[.07] bg-[#090a0b]/95 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div className="flex min-w-0 items-center gap-3"><img src="/booth-marketing-logo.png" alt="Booth Marketing" className="w-[105px] max-w-[35vw] sm:w-[125px] lg:hidden"/><span className="hidden text-[11px] font-semibold text-[#8b8c92] lg:block">{section}</span></div><div className="flex shrink-0 items-center gap-2"><span className="hidden rounded-full border border-white/[.07] bg-white/[.025] px-3 py-1.5 text-[9px] uppercase tracking-[.14em] text-[#696a70] sm:inline">Website lead tracker</span><details className="group relative lg:hidden"><summary aria-label="Open admin menu" className="flex min-h-[44px] min-w-[44px] cursor-pointer list-none items-center justify-center rounded-xl border border-white/[.12] text-[#e7e0d5] marker:hidden [&::-webkit-details-marker]:hidden"><Menu className="h-5 w-5"/></summary><div className="absolute right-0 top-[calc(100%+10px)] z-50 w-[min(82vw,270px)] rounded-2xl border border-white/[.12] bg-[#111315] p-2 shadow-2xl"><p className="px-3 py-2 text-[10px] font-semibold uppercase tracking-widest text-[#77787e]">Admin menu</p>{nav.map(item=>{const Icon=item.icon;return <Link key={item.href} href={item.href} className="flex min-h-[44px] items-center gap-3 rounded-xl px-3 text-[13px] text-[#e6e6e6] hover:bg-white/[.06]"><Icon className="h-4 w-4"/>{item.label}</Link>})}<a href="/api/admin/leads/export" className="flex min-h-[44px] items-center gap-3 rounded-xl px-3 text-[13px] text-[#e6e6e6] hover:bg-white/[.06]"><Download className="h-4 w-4"/>Export CSV</a><Link href="/" target="_blank" className="flex min-h-[44px] items-center gap-3 rounded-xl px-3 text-[13px] text-[#e6e6e6] hover:bg-white/[.06]"><ExternalLink className="h-4 w-4"/>View website</Link><form action="/api/admin/logout" method="post"><button className="flex min-h-[44px] w-full items-center gap-3 rounded-xl px-3 text-[13px] text-[#e6e6e6] hover:bg-white/[.06]"><LogOut className="h-4 w-4"/>Log out</button></form></div></details></div></header><nav aria-label="Quick admin navigation" className="sticky top-[62px] z-20 flex gap-2 overflow-x-auto border-b border-white/[.07] bg-[#0b0d0e]/98 px-3 py-2 lg:hidden">{nav.map(item=>{const Icon=item.icon,active=section===item.label;return <Link key={item.href} href={item.href} className={`flex shrink-0 items-center gap-2 min-h-[44px] rounded-lg px-4 py-3 text-[12px] font-medium ${active?'bg-[#efe3cf] text-[#151515]':'text-[#8b8c92]'}`}><Icon className="h-3.5 w-3.5"/>{item.label}</Link>})}<a href="/api/admin/leads/export" className="flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-[10px] font-medium text-[#8b8c92]"><Download className="h-3.5 w-3.5"/>Export</a></nav><main className="min-w-0 px-3 py-5 sm:px-6 sm:py-9 lg:px-8 xl:px-10">{children}</main></div>
 </div>
}
