import { ArrowRight } from 'lucide-react'
import Link from 'next/link'
import SiteHeader from '../../components/SiteHeader'
import SiteFooter from '../../components/SiteFooter'
const prototypes=[
['Lead Qualification System','Incoming enquiries need reviewing before the right person can act.','Extract relevant details, categorise the enquiry, prepare a CRM update and route it.','A person owns commercial qualification and the customer conversation.'],
['Customer Enquiry Assistant','Teams repeatedly answer predictable questions or manually route requests.','Use approved information to prepare answers or direct the request to the correct team.','People handle exceptions, sensitive cases and judgement calls.'],
['Automated Follow-Up System','Opportunities go quiet because follow-up depends on memory.','Track agreed conditions and trigger or prepare the appropriate follow-up.','The salesperson owns the relationship and can override the workflow.'],
['Document Processing System','Routine documents are opened, read and re-keyed into other systems.','Extract defined fields, validate them and prepare the information for the next step.','Exceptions and low-confidence cases are escalated for review.'],
['Internal Knowledge Assistant','Staff lose time searching documents and asking colleagues for information.','Retrieve answers from an approved internal knowledge set with source context.','The business controls the knowledge sources and what decisions still require a person.']
]
export default function Prototypes(){return <main className="booth-public min-h-screen"><SiteHeader/><section className="border-b booth-rule bg-[#080808]"><div className="booth-container py-12 sm:py-16 lg:py-20"><p className="booth-kicker">Prototype Library</p><h1 className="booth-display booth-mobile-heading mt-5 max-w-[900px]">Don't imagine automation. See the process.</h1><p className="booth-copy booth-mobile-copy mt-5 max-w-[720px]">These demonstration systems show how common business processes can move from manual handling to a controlled automated workflow. They are examples, not client performance claims.</p></div></section><section className="booth-section"><div className="booth-container"><div className="border-t booth-rule">{prototypes.map(([name,problem,automation,human],i)=><article key={name} className="border-b booth-rule py-8"><div className="grid gap-7 lg:grid-cols-[70px_280px_1fr]"><span className="font-mono text-[10px] text-[#5f5f5f]">0{i+1}</span><div><p className="booth-kicker">Demonstration System</p><h2 className="booth-display mt-3 text-[28px]">{name}</h2></div><div className="grid gap-4 sm:grid-cols-3"><div><p className="booth-kicker">Problem</p><p className="booth-copy mt-3 text-[12px] leading-6">{problem}</p></div><div><p className="booth-kicker">Automated process</p><p className="booth-copy mt-3 text-[12px] leading-6">{automation}</p></div><div><p className="booth-kicker">Human role</p><p className="booth-copy mt-3 text-[12px] leading-6">{human}</p></div></div></div></article>)}</div><p className="mt-7 max-w-[700px] text-[11px] leading-6 text-[#666]">Independent demonstration concepts. They are not presented as commissioned client systems and no performance result is implied.</p><Link href="/automation-audit" className="booth-primary mt-7 inline-flex items-center">Find an Opportunity<ArrowRight className="ml-2 h-4 w-4"/></Link></div></section><SiteFooter/></main>}