import { ArrowRight, ExternalLink } from 'lucide-react'
import Image from 'next/image'
import Link from 'next/link'
import SiteHeader from '../../components/SiteHeader'
import SiteFooter from '../../components/SiteFooter'

const automation=[
['Lead Qualification System','Incoming enquiries need reviewing before the right person can act.','Extract relevant details, categorise the enquiry, prepare a CRM update and route it.','A person owns commercial qualification and the customer conversation.'],
['Customer Enquiry Assistant','Teams repeatedly answer predictable questions or manually route requests.','Use approved information to prepare answers or direct the request to the correct team.','People handle exceptions, sensitive cases and judgement calls.'],
['Automated Follow-Up System','Opportunities go quiet because follow-up depends on memory.','Track agreed conditions and trigger or prepare the appropriate follow-up.','The salesperson owns the relationship and can override the workflow.'],
['Document Processing System','Routine documents are opened, read and re-keyed into other systems.','Extract defined fields, validate them and prepare the information for the next step.','Exceptions and low-confidence cases are escalated for review.'],
['Internal Knowledge Assistant','Staff lose time searching documents and asking colleagues for information.','Retrieve answers from an approved internal knowledge set with source context.','The business controls the knowledge sources and what decisions still require a person.']
]
const previous=[
{sector:'Commercial Insurance',name:'Northstead Commercial Risk',href:'/work/northstead-commercial-risk',live:'https://northstead-commercial-risk.vercel.app',preview:'/work/northstead.png',copy:'An independent concept showing how a complex B2B service can be repositioned around buyer relevance, confidence and a clear next action.'},
{sector:'Hospitality / Nightlife',name:'Purple Door Leeds',href:'/work/purple-door-leeds',live:'https://purple-door-nine.vercel.app',preview:'/work/purple-door.png',copy:'A multi-page venue concept demonstrating premium positioning, information architecture and conversion-focused visitor journeys.'},
{sector:'Fitness / Local Business',name:'Graft Haus Gym',href:'/work/graft-haus-gym',live:'https://graft-haus-gym.vercel.app',preview:'/work/graft-haus.png',copy:'A local fitness concept showing how strong brand energy can be turned into a clearer membership journey.'}
]
export default function Prototypes(){return <main className="booth-public min-h-screen"><SiteHeader/>
<section className="border-b booth-rule bg-[#080808]"><div className="booth-container py-12 sm:py-16 lg:py-20"><p className="booth-kicker">Prototype Library</p><h1 className="booth-display booth-mobile-heading mt-5 max-w-[900px]">Don't imagine the thinking. See it.</h1><p className="booth-copy booth-mobile-copy mt-5 max-w-[740px]">Explore automation demonstrations and previous independent prototypes. They are here as proof of how Booth thinks, structures problems and turns an idea into something tangible. Independent concepts are labelled clearly and are not presented as commissioned client work.</p></div></section>
<section className="booth-section border-b booth-rule"><div className="booth-container"><p className="booth-kicker">01 / Automation Prototypes</p><h2 className="booth-display mt-4 max-w-[760px] text-[32px] leading-[1.04] sm:text-[44px]">Business processes redesigned as controlled workflows.</h2><div className="mt-8 border-t booth-rule">{automation.map(([name,problem,process,human],i)=><article key={name} className="border-b booth-rule py-8"><div className="grid gap-7 lg:grid-cols-[70px_280px_1fr]"><span className="font-mono text-[10px] text-[#5f5f5f]">0{i+1}</span><div><p className="booth-kicker">Demonstration System</p><h3 className="booth-display mt-3 text-[28px]">{name}</h3></div><div className="grid gap-4 sm:grid-cols-3"><div><p className="booth-kicker">Problem</p><p className="booth-copy mt-3 text-[12px] leading-6">{problem}</p></div><div><p className="booth-kicker">Automated process</p><p className="booth-copy mt-3 text-[12px] leading-6">{process}</p></div><div><p className="booth-kicker">Human role</p><p className="booth-copy mt-3 text-[12px] leading-6">{human}</p></div></div></div></article>)}</div></div></section>
<section className="booth-section border-b booth-rule bg-[#080808]"><div className="booth-container"><p className="booth-kicker">02 / Previous Proof Proxies</p><h2 className="booth-display mt-4 max-w-[820px] text-[32px] leading-[1.04] sm:text-[44px]">Previous prototypes from Booth's earlier builds.</h2><p className="booth-copy mt-5 max-w-[720px] text-[14px] leading-7">These projects are retained because they show the ability to research a business, shape a proposition and turn it into a working digital prototype. They are supporting proof of execution, not claims that each business commissioned an AI automation system.</p><div className="mt-9 grid gap-6 lg:grid-cols-3">{previous.map((p,i)=><article key={p.name} className="overflow-hidden rounded-lg border booth-rule bg-[#0b0b0b]"><Link href={p.href} className="group relative block aspect-[16/10] overflow-hidden border-b booth-rule"><Image src={p.preview} alt={p.name+' prototype'} fill sizes="(min-width:1024px) 33vw, 100vw" className="object-cover object-top transition duration-300 group-hover:scale-[1.01]"/></Link><div className="p-5"><p className="booth-kicker">0{i+1} / {p.sector} / Independent Concept</p><h3 className="booth-display mt-4 text-[25px]">{p.name}</h3><p className="booth-copy mt-3 text-[12px] leading-6">{p.copy}</p><div className="mt-5 flex flex-wrap gap-5"><Link href={p.href} className="booth-text-link">Case study<ArrowRight className="ml-2 h-4 w-4"/></Link><a href={p.live} target="_blank" rel="noreferrer" className="booth-text-link">Live prototype<ExternalLink className="ml-2 h-3.5 w-3.5"/></a></div></div></article>)}</div><p className="mt-6 max-w-[820px] text-[10px] leading-5 text-[#666]">Northstead Commercial Risk, Purple Door Leeds and Graft Haus Gym are independent concept work. They are not presented as commissioned client projects and no performance claims are implied.</p></div></section>
<section className="booth-section"><div className="booth-container"><div className="border-y booth-rule py-10 lg:flex lg:items-end lg:justify-between lg:gap-10"><div><p className="booth-kicker">Your process</p><h2 className="booth-display mt-4 max-w-[760px] text-[36px] leading-[1.02] sm:text-[50px]">Now show us what is wasting time in your business.</h2></div><Link href="/automation-audit" className="booth-primary mt-7 inline-flex items-center lg:mt-0">Find an Opportunity<ArrowRight className="ml-2 h-4 w-4"/></Link></div></div></section><SiteFooter/></main>}
